# Generated by Django 3.2.7 on 2021-10-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_auto_20211006_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='updated_date',
            new_name='date_close',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='created_date',
            new_name='date_enroll',
        ),
    ]
