# Generated by Django 3.2.7 on 2021-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_auto_20211006_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
