# Generated by Django 3.2.7 on 2021-10-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211006_1927'),
        ('students', '0003_alter_student_nick_name'),
        ('enrollments', '0008_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.student'),
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
    ]
