# Generated by Django 3.2.7 on 2021-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_auto_20211008_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
