# Generated by Django 3.2.7 on 2021-10-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nick_name',
            field=models.CharField(max_length=200, verbose_name='Surname'),
        ),
    ]
