# Generated by Django 3.2.7 on 2021-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='holder_image',
            field=models.URLField(null=True),
        ),
    ]
