# Generated by Django 3.2.7 on 2021-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holder_image',
            field=models.URLField(default='http://keeps.com.br'),
        ),
    ]
