# Generated by Django 3.2.7 on 2021-10-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('courses', '0005_auto_20211006_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='Description', max_length=200, verbose_name='Description'),
        ),
    ]
