# Generated by Django 3.2.7 on 2021-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211008_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='mandatory',
            field=models.BooleanField(blank=True, null=True, verbose_name='Mandatory'),
        ),
    ]
