# Generated by Django 3.2.7 on 2021-10-07 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(default='Description', max_length=200, verbose_name='Name')),
                ('content_type', models.CharField(choices=[('F', 'File'), ('L', 'Link')], max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Content',
                'db_table': 'content',
            },
        ),
    ]
