# Generated by Django 2.2 on 2021-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(default='www.arroz.com.br', max_length=1000, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
